### PR TITLE
Feature: optional attributes

### PR DESCRIPTION
**Pull request by jdigory**
Let me know if this works for you. Thanks!

### CODE REVIEW

**Comment by nupfel** [comment]
awesome! that's helpful :) thank you for adding tests as well!

and sorry for the late response, i'm currently on holiday and didn't see your pull request earlier.

i guess this is kind of the first part of #4, which is great :)
what would be a good example for this kind of use for optional attributes?
i'm personally not quite happy using the question mark as the indicator for an optional argument because it's too easily confused with the URI parameters delimiter, but it also makes sense thinking about regex where it indicates an optional character.
i chose ':' for variable mandatory attributes, because it's what all the web app frameworks use.

**Comment by jdigory** [comment]
I see Dancer2 uses `'/hello/:name?'` with the `?` mark postfixed, so that may be better.

I am working on an integration of MailChimp's API v3, and just thought that we could save a method if we could have optional attributes. 

E.g. no optional support:

```
batch     => { path => 'batches/:batch_id' },
batches => { path => 'batches' },
```

However, the above is probably a nicer way to know that you just want a "batch" (singular) as opposed to "batches" (plural). I looked at some of your WebService modules, and liked how you did it. :-)

E.g. with optional support that could become:

```
batches => { path => 'batches/:batch_id?' },
```

MailChimp API docs for "batches" (click "Read") http://developer.mailchimp.com/documentation/mailchimp/reference/batches/

**Comment by jdigory** [comment]
Just a note that I added a commit 6d984a4 to do the optional attributes better.

**Comment by nupfel** [comment]
thanks a lot! i think from a client user view the distinction between singular and plural ose of batch/batches is very important. they are 2 completely distinctive endpoints and commands and while the optional attribute saves code lines it's one of the examples that actually make it harder to read and understand the code as well as use it. you don't really save much time having to have 2 separate commands and technically those attributes are not optional at all, they are just separate commands forced into one, which i definitely don't like to encourage. i hope that makes sense.

**Pull request closed without merging**
