### PR TITLE
Remove smartmatch usage

### LINKED ISSUE #31: Smartmatch is deprecated in 5.30.0
As of perl 5.38.0 smartmatch is deprected.

Probably should remove all references to it.

```
given is deprecated at /vendor/local/lib/perl5/Web/API.pm line 376.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 377.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 383.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 384.
given is deprecated at /vendor/local/lib/perl5/Web/API.pm line 417.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 418.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 424.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 425.
given is deprecated at /vendor/local/lib/perl5/Web/API.pm line 450.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 451.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 452.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 456.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 466.
when is deprecated at /vendor/local/lib/perl5/Web/API.pm line 472.
Smartmatch is deprecated at /vendor/local/lib/perl5/Web/API.pm line 722.
Smartmatch is deprecated at /vendor/local/lib/perl5/Web/API.pm line 919.
```

### PR DESCRIPTION
**Pull request by mschout**
Smartmatch is officially deprecated as of Perl 5.38.0

fixes #31

### CODE REVIEW

**Comment by nupfel** [comment]
awesome, thank you! I did not expect this module to still be in use!

**Comment by mschout** [comment]
Thanks.  If you are curious, for me, the issue is that its a dependency of `Mail::Chimp3` which I am using.

**Comment by mpessotto-endpoint** [comment]
Hi, could you please make a CPAN release with this patch?

**Comment by nupfel** [comment]
sorry for the huge delay in sorting this out, but version 2.8 is now on CPAN as a new release including this PR

**Pull request merged**
